name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@main
      env:
        HUGO_VERSION: 0.101.0
        HUGO_EXTENDED: true
        TARGET_REPO: zanna-research/zanna-research.github.io
        TOKEN: ${{ secrets.WEB_DEPLOY }}
        CNAME: zanna-research.github.io
        HUGO_ARGS: --debug
        GO_VERSION: 1.17
